CREATE TABLE IF NOT EXISTS pengguna (
    id_user INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    jalan VARCHAR(200) NOT NULL,
    kota VARCHAR(100) NOT NULL,
    provinsi VARCHAR(100) NOT NULL,
    negara VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS pengguna_telp (
    id_user INT NOT NULL,
    nomor_telepon VARCHAR(50) NOT NULL,
    PRIMARY KEY (id_user, nomor_telepon),
    FOREIGN KEY (id_user) REFERENCES pengguna(id_user)
);

INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Suci Budiyanto', 'latuponounggul@example.org', 'Jl. Kebonjati No. 092', 'Blitar', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Balapati Laksmiwati', 'ynashiruddin@example.org', 'Gg. Merdeka No. 680', 'Blitar', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Talia Pangestu', 'tarihoranvirman@example.org', 'Jalan Monginsidi No. 181', 'Lhokseumawe', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Okta Sihotang, M.Pd', 'sadina70@example.com', 'Jl. Gegerkalong Hilir No. 685', 'Jayapura', 'Papua', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ibrani Kusumo', 'gfirgantoro@example.org', 'Gg. Indragiri No. 409', 'Mamuju', 'Sulawesi Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Mulyanto Maryati', 'usalahudin@example.com', 'Gg. Rawamangun No. 599', 'Mamuju', 'Sulawesi Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Raina Prasasta', 'cahyosuartini@example.net', 'Jl. Suryakencana No. 75', 'Tasikmalaya', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dr. Elisa Lazuardi, S.Farm', 'hana82@example.net', 'Jalan Rajawali Timur No. 36', 'Ambon', 'Maluku', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Kenes Anggraini', 'pratamaani@example.com', 'Jl. Dipatiukur No. 47', 'Jayapura', 'Papua', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Victoria Nasyidah', 'wmegantara@example.com', 'Jl. M.T Haryono No. 52', 'Makassar', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dwi Saptono', 'nardihasanah@example.com', 'Jalan Antapani Lama No. 1', 'Samarinda', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Candra Utama', 'wasitaeka@example.org', 'Gg. Otto Iskandardinata No. 19', 'Purwokerto', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Siska Marbun', 'tinapadmasari@example.org', 'Gang Waringin No. 96', 'Banjarmasin', 'Kalimantan Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Darmanto Farida', 'djanuar@example.net', 'Gang Rajawali Timur No. 88', 'Tidore', 'Maluku Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dt. Paiman Pangestu, M.Pd', 'mahfud21@example.com', 'Jalan Kutisari Selatan No. 2', 'Surabaya', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Drs. Ibun Saragih, M.Pd', 'wijayantikarman@example.com', 'Jl. PHH. Mustofa No. 826', 'Binjai', 'Sumatera Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Maimunah Salahudin', 'prasetyohardi@example.com', 'Gang Laswi No. 870', 'Solo', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dr. Heru Lailasari', 'triyanti@example.net', 'Gang Kutisari Selatan No. 953', 'Denpasar', 'Bali', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Fitria Halim', 'cahyoadriansyah@example.net', 'Gg. R.E Martadinata No. 120', 'Binjai', 'Sumatera Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Zahra Suryatmi', 'kenari15@example.net', 'Gang Yos Sudarso No. 1', 'Tasikmalaya', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Humaira Sitorus', 'hasan07@example.com', 'Gang H.J Maemunah No. 89', 'Malang', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('drg. Ismail Damanik', 'suartinikartika@example.com', 'Gang Bangka Raya No. 882', 'Manado', 'Sulawesi Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Yosef Agustina', 'suryonolidya@example.net', 'Jalan HOS. Cokroaminoto No. 6', 'Tegal', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Mulyono Pradana', 'bnasyidah@example.com', 'Jl. Merdeka No. 04', 'Parepare', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Banawi Nashiruddin, S.Psi', 'prasetyawisnu@example.org', 'Gang Merdeka No. 8', 'Pekanbaru', 'Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dt. Karya Mandala', 'suryonorafi@example.org', 'Jalan Tebet Barat Dalam No. 48', 'Tarakan', 'Kalimantan Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Prakosa Halimah, S.Ked', 'prabowovera@example.com', 'Jl. HOS. Cokroaminoto No. 2', 'Binjai', 'Sumatera Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Puti Tami Suryono, S.E.', 'rachel46@example.org', 'Jalan Cihampelas No. 17', 'Batu', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Lidya Sitorus', 'hanahidayanto@example.org', 'Jalan Setiabudhi No. 972', 'Magelang', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Puti Anita Hutapea, M.TI.', 'palastriniyaga@example.com', 'Gang Monginsidi No. 547', 'Denpasar', 'Bali', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Novi Rajasa', 'vera83@example.com', 'Gg. Cempaka No. 9', 'Jakarta', 'DKI Jakarta', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Clara Nashiruddin', 'wijayantifarhunnisa@example.net', 'Jalan Sukajadi No. 684', 'Lhokseumawe', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dr. Prayitna Winarno, S.Pt', 'lsinaga@example.com', 'Jalan HOS. Cokroaminoto No. 9', 'Sorong', 'Papua Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dr. Dariati Simanjuntak, S.Kom', 'fnarpati@example.net', 'Gg. Cempaka No. 5', 'Solo', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Hj. Kamila Sitompul', 'aryanimaimunah@example.com', 'Jl. Indragiri No. 471', 'Palopo', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Cut Karimah Prasetyo, S.H.', 'apermata@example.org', 'Gg. Rajawali Barat No. 67', 'Samarinda', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Mahdi Wibisono', 'prasetyachandra@example.org', 'Gg. Gardujati No. 9', 'Madiun', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Janet Pangestu', 'pratiwibudi@example.net', 'Jalan Rawamangun No. 44', 'Tanjungpinang', 'Kepulauan Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Lanjar Nasyiah', 'lasmono56@example.com', 'Jl. Sukajadi No. 93', 'Mojokerto', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Emong Setiawan, S.I.Kom', 'saptonomahesa@example.org', 'Jalan Pasteur No. 9', 'Metro', 'Lampung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Laras Budiman', 'padmazulkarnain@example.org', 'Jalan Asia Afrika No. 1', 'Tegal', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('H. Adikara Mulyani, S.Ked', 'winarsihade@example.com', 'Jl. Suniaraja No. 94', 'Manokwari', 'Papua Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Sutan Tugiman Sinaga, S.E.I', 'hardana30@example.net', 'Gang Ciwastra No. 64', 'Palu', 'Sulawesi Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Drs. Aditya Rajata', 'lmarpaung@example.net', 'Gang W.R. Supratman No. 00', 'Tanjungpinang', 'Kepulauan Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gina Pradana', 'samsulwahyudin@example.org', 'Gg. Cihampelas No. 810', 'Dumai', 'Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Mulyono Mangunsong', 'dabukkedagel@example.com', 'Jl. Abdul Muis No. 427', 'Dumai', 'Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Kunthara Aryani', 'jaswadi26@example.org', 'Jl. Surapati No. 77', 'Bekasi', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Maryanto Damanik', 'hassanahsalimah@example.net', 'Jalan Peta No. 542', 'Ambon', 'Maluku', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Puti Queen Mayasari, M.M.', 'bsiregar@example.net', 'Gang Peta No. 600', 'Palopo', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ikin Prakasa', 'eirawan@example.org', 'Jalan Indragiri No. 0', 'Gorontalo', 'Gorontalo', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Mila Ramadan', 'kembawijayanti@example.org', 'Jl. Cikutra Timur No. 31', 'Langsa', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Puti Jelita Tamba, S.E.I', 'hardiansyahpuji@example.org', 'Jl. Pasir Koja No. 15', 'Cirebon', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Rahmi Anggriawan', 'uli95@example.org', 'Gang Rajiman No. 24', 'Samarinda', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Mariadi Hidayanto, M.TI.', 'anamaulana@example.com', 'Gg. Ciumbuleuit No. 167', 'Sukabumi', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Erik Lazuardi', 'utamamuni@example.org', 'Gg. Ciwastra No. 04', 'Balikpapan', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Harto Mandala', 'rjanuar@example.org', 'Jl. Ahmad Dahlan No. 246', 'Gorontalo', 'Gorontalo', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Kasusra Sitorus', 'emil96@example.org', 'Jalan Raya Setiabudhi No. 42', 'Palangkaraya', 'Kalimantan Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Paramita Wahyuni', 'maheswaravivi@example.net', 'Jl. Bangka Raya No. 327', 'Samarinda', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ian Firgantoro', 'prayoga26@example.com', 'Gang Jamika No. 243', 'Medan', 'Sumatera Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Eli Kurniawan', 'maheswarakarja@example.org', 'Gg. Cempaka No. 136', 'Semarang', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Jono Pertiwi', 'sihombingrahmat@example.net', 'Gang W.R. Supratman No. 989', 'Medan', 'Sumatera Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R.M. Jumadi Astuti', 'galionomayasari@example.org', 'Gang R.E Martadinata No. 5', 'Salatiga', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Joko Hakim', 'vsaputra@example.com', 'Gg. Rungkut Industri No. 5', 'Sungai Penuh', 'Jambi', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Leo Dabukke', 'bagiya72@example.net', 'Gg. Cikutra Barat No. 6', 'Cimahi', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tgk. Lala Prasasta', 'adhiarja32@example.net', 'Jalan Sukajadi No. 97', 'Batam', 'Kepulauan Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ilsa Gunawan', 'lastuti@example.com', 'Jalan Gardujati No. 209', 'Tegal', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gamblang Safitri, S.I.Kom', 'evasirait@example.com', 'Gg. Sadang Serang No. 199', 'Depok', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Viktor Mardhiyah', 'darmajisaefullah@example.com', 'Gang Abdul Muis No. 26', 'Cimahi', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R. Luwar Dongoran', 'dlestari@example.net', 'Jalan Jayawijaya No. 647', 'Sukabumi', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('dr. Sabrina Wijaya, M.Farm', 'hutapealanggeng@example.com', 'Jalan Cempaka No. 23', 'Tangerang', 'Banten', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Maida Thamrin', 'gnarpati@example.org', 'Jl. Jayawijaya No. 7', 'Samarinda', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Kajen Nashiruddin', 'vanesa67@example.net', 'Gang Lembong No. 75', 'Yogyakarta', 'DI Yogyakarta', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Zaenab Hidayat', 'cahya69@example.org', 'Gg. Sadang Serang No. 19', 'Balikpapan', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Bakti Astuti, M.Pd', 'artapangestu@example.com', 'Jl. KH Amin Jasuta No. 27', 'Bengkulu', 'Bengkulu', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Cut Zulaikha Wahyuni', 'capa42@example.com', 'Jalan Sukabumi No. 1', 'Pekanbaru', 'Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tantri Hartati', 'citra66@example.net', 'Jl. Indragiri No. 734', 'Binjai', 'Sumatera Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ian Kuswandari', 'luthfi59@example.com', 'Jl. Monginsidi No. 03', 'Palembang', 'Sumatera Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Chelsea Rahimah, S.Ked', 'ssafitri@example.net', 'Gang Moch. Toha No. 5', 'Jakarta', 'DKI Jakarta', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Anita Dongoran', 'putiwaluyo@example.com', 'Gang Lembong No. 67', 'Cirebon', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dacin Pradipta', 'darsirahfujiati@example.net', 'Jl. Jakarta No. 464', 'Madiun', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Maimunah Maheswara', 'spermata@example.org', 'Gg. Cikutra Barat No. 6', 'Magelang', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Vanya Napitupulu', 'ypradana@example.com', 'Jl. HOS. Cokroaminoto No. 352', 'Ambon', 'Maluku', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Endra Mansur', 'gutami@example.com', 'Gang Cikapayang No. 50', 'Pekalongan', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ilyas Santoso', 'lalita72@example.net', 'Jl. Siliwangi No. 54', 'Blitar', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Cemani Kuswandari, S.T.', 'olga96@example.org', 'Jalan Rawamangun No. 14', 'Tarakan', 'Kalimantan Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gatot Suartini', 'jnasyidah@example.org', 'Gang Ahmad Yani No. 31', 'Semarang', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Eli Namaga', 'ulya95@example.com', 'Gang Merdeka No. 95', 'Tasikmalaya', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('drg. Cahyono Pratama, S.Pd', 'xprasetyo@example.org', 'Jl. Medokan Ayu No. 0', 'Semarang', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Sabrina Hartati, S.Gz', 'eman31@example.org', 'Gg. Cikutra Barat No. 4', 'Batam', 'Kepulauan Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Anggabaya Wulandari', 'wpangestu@example.net', 'Jalan Kutisari Selatan No. 548', 'Langsa', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Puspa Sitompul', 'gamblang37@example.com', 'Gg. Abdul Muis No. 888', 'Bogor', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Paramita Prabowo', 'samosirbakiman@example.org', 'Jalan Kiaracondong No. 6', 'Bengkulu', 'Bengkulu', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ajimat Prayoga', 'pnainggolan@example.org', 'Gang Antapani Lama No. 45', 'Sukabumi', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Devi Kurniawan', 'daniswarahalimah@example.net', 'Gang Astana Anyar No. 9', 'Bengkulu', 'Bengkulu', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Cager Prayoga', 'prastutihendra@example.com', 'Gg. Cempaka No. 00', 'Batam', 'Kepulauan Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Drs. Ratih Jailani', 'kurniawanharjaya@example.org', 'Gang Otto Iskandardinata No. 8', 'Tidore', 'Maluku Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Syahrini Laksita', 'ejailani@example.net', 'Gang Medokan Ayu No. 059', 'Depok', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('dr. Ira Hakim, S.E.I', 'ozy06@example.com', 'Gg. H.J Maemunah No. 173', 'Binjai', 'Sumatera Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Indah Adriansyah, S.I.Kom', 'ihabibi@example.org', 'Gg. Stasiun Wonokromo No. 59', 'Purwokerto', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Daliono Utama', 'febisusanti@example.org', 'Jalan Rungkut Industri No. 86', 'Sabang', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dt. Jayadi Suryono, S.E.', 'jayengnasyiah@example.org', 'Jalan Waringin No. 53', 'Kediri', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gada Sirait, S.Pd', 'capafirmansyah@example.com', 'Jalan HOS. Cokroaminoto No. 48', 'Bogor', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ayu Puspasari, S.Pt', 'siti25@example.org', 'Gang Pacuan Kuda No. 948', 'Pekanbaru', 'Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Pangestu Purnawati', 'wahyuniicha@example.org', 'Jalan W.R. Supratman No. 19', 'Tanjungpinang', 'Kepulauan Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ana Sinaga, S.E.', 'sitoruseko@example.org', 'Gg. Cikutra Timur No. 42', 'Tanjung Selor', 'Kalimantan Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ade Nasyidah', 'widiastutiade@example.net', 'Jl. Merdeka No. 78', 'Tegal', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dr. Cager Nurdiyanti, S.Kom', 'nainggolanmustofa@example.org', 'Gang Laswi No. 63', 'Binjai', 'Sumatera Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Elvin Maryadi', 'purnawatigarda@example.net', 'Gg. Peta No. 484', 'Parepare', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Lamar Yolanda, M.Pd', 'ewinarsih@example.com', 'Jalan BKR No. 714', 'Ambon', 'Maluku', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Nilam Rahimah, M.Ak', 'pancadamanik@example.net', 'Jalan Laswi No. 786', 'Jambi', 'Jambi', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gasti Hasanah', 'hhartati@example.com', 'Jl. Moch. Ramdan No. 72', 'Bontang', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Sutan Gandi Mansur', 'hhandayani@example.com', 'Jl. Jakarta No. 2', 'Depok', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Cakrabirawa Irawan', 'dwidiastuti@example.com', 'Jl. Suryakencana No. 4', 'Palopo', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Puti Kani Suryono', 'haryantodadi@example.org', 'Jalan Yos Sudarso No. 574', 'Ternate', 'Maluku Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Galang Padmasari, M.Kom.', 'nprasetya@example.net', 'Jl. Rumah Sakit No. 17', 'Yogyakarta', 'DI Yogyakarta', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Kasim Mangunsong, S.I.Kom', 'tambasatya@example.net', 'Gg. R.E Martadinata No. 467', 'Makassar', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Vivi Agustina', 'oktavianieka@example.org', 'Gang Laswi No. 07', 'Banjarmasin', 'Kalimantan Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Yani Palastri', 'bahuwarna07@example.org', 'Jalan Kutisari Selatan No. 7', 'Banda Aceh', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Karna Irawan', 'dhandayani@example.net', 'Gang Peta No. 60', 'Tasikmalaya', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tania Palastri', 'karsawijayanti@example.org', 'Gg. Otto Iskandardinata No. 454', 'Bontang', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('drg. Okto Irawan', 'vanya79@example.com', 'Jalan M.H Thamrin No. 340', 'Batam', 'Kepulauan Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Drs. Raihan Januar', 'nurainibelinda@example.net', 'Gg. Surapati No. 341', 'Bandar Lampung', 'Lampung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('KH. Kamidin Riyanti, S.H.', 'aswanimaryadi@example.com', 'Jl. Pasir Koja No. 963', 'Sabang', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Galang Lazuardi, M.Pd', 'ilyas51@example.com', 'Gg. Dipenogoro No. 51', 'Blitar', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Carla Hardiansyah', 'damanikvega@example.net', 'Gang Stasiun Wonokromo No. 23', 'Manado', 'Sulawesi Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dr. Hasta Wulandari', 'fnovitasari@example.net', 'Jalan Bangka Raya No. 20', 'Pekanbaru', 'Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Joko Gunawan', 'crajasa@example.com', 'Gang W.R. Supratman No. 95', 'Magelang', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Saadat Yuniar', 'warjimarbun@example.com', 'Jl. Sadang Serang No. 247', 'Manokwari', 'Papua Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gasti Saefullah', 'namagaalambana@example.com', 'Jalan Bangka Raya No. 795', 'Bontang', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Hj. Ani Usada', 'dasadamanik@example.org', 'Jalan Kendalsari No. 281', 'Sofifi', 'Maluku Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Puti Rahmi Hidayat', 'emong87@example.net', 'Jl. Rajawali Barat No. 9', 'Binjai', 'Sumatera Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Aslijan Adriansyah', 'mulyaniwira@example.com', 'Jalan Suniaraja No. 15', 'Bogor', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Septi Maryati', 'warsa94@example.org', 'Jalan Joyoboyo No. 2', 'Ambon', 'Maluku', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Kasiyah Saputra', 'sabrina05@example.org', 'Jalan Yos Sudarso No. 9', 'Mataram', 'Nusa Tenggara Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Indah Yulianti', 'nyulianti@example.com', 'Gang Dipatiukur No. 061', 'Tanjung Selor', 'Kalimantan Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Karsana Siregar', 'firmansyahganjaran@example.net', 'Jl. Cempaka No. 109', 'Tanjung Selor', 'Kalimantan Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('H. Galiono Purnawati', 'saputrahana@example.com', 'Gg. Cihampelas No. 01', 'Tasikmalaya', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gaman Kuswoyo', 'salahudinsafina@example.com', 'Gang Rajiman No. 801', 'Makassar', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R. Anastasia Puspita', 'elinuraini@example.org', 'Gg. Tebet Barat Dalam No. 19', 'Tangerang', 'Banten', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Umaya Fujiati', 'lazuardiumar@example.com', 'Jl. Cikutra Barat No. 47', 'Semarang', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Mila Handayani', 'ibudiman@example.org', 'Gang Kiaracondong No. 98', 'Langsa', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tgk. Karen Lazuardi, S.Gz', 'anggrainicawisadi@example.net', 'Gg. Setiabudhi No. 571', 'Serang', 'Banten', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Niyaga Kuswandari', 'gandewa96@example.com', 'Jalan Ahmad Dahlan No. 777', 'Bengkulu', 'Bengkulu', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Vicky Setiawan', 'emilsuwarno@example.com', 'Gg. Otto Iskandardinata No. 3', 'Tasikmalaya', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gatra Hutagalung', 'ganepdongoran@example.com', 'Gg. Dipenogoro No. 4', 'Kendari', 'Sulawesi Tenggara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Elisa Dabukke', 'anggriawaneko@example.org', 'Gg. Abdul Muis No. 7', 'Banjarmasin', 'Kalimantan Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('H. Edward Permadi, S.I.Kom', 'eka32@example.net', 'Gg. Ahmad Dahlan No. 46', 'Sabang', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tina Waluyo', 'ositompul@example.com', 'Gang Joyoboyo No. 812', 'Jambi', 'Jambi', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tgk. Diah Wacana, S.Pd', 'anastasiapratama@example.com', 'Gg. HOS. Cokroaminoto No. 1', 'Balikpapan', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Johan Kuswoyo', 'gildafirgantoro@example.org', 'Jalan Astana Anyar No. 38', 'Palopo', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Hesti Nurdiyanti', 'laksana00@example.net', 'Gg. Kebonjati No. 75', 'Manokwari', 'Papua Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Devi Manullang', 'doktaviani@example.com', 'Gang Bangka Raya No. 7', 'Gorontalo', 'Gorontalo', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Kayun Napitupulu', 'sabriadriansyah@example.com', 'Gg. Rawamangun No. 99', 'Tegal', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('dr. Rahmi Kurniawan, S.Farm', 'saadat28@example.com', 'Jalan Cikutra Timur No. 606', 'Bandung', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Darimin Tamba', 'titi41@example.net', 'Jl. Sukabumi No. 29', 'Metro', 'Lampung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Bakianto Sinaga, M.Ak', 'qmelani@example.net', 'Jalan Merdeka No. 5', 'Dumai', 'Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dr. Adinata Hidayanto', 'kajenkuswoyo@example.net', 'Gang Pacuan Kuda No. 4', 'Bukittinggi', 'Sumatera Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R.M. Damar Irawan', 'kmanullang@example.org', 'Jl. Ir. H. Djuanda No. 39', 'Banda Aceh', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ajeng Siregar', 'mhabibi@example.net', 'Jl. Suryakencana No. 91', 'Tasikmalaya', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gandi Sitompul', 'tasnim03@example.net', 'Jl. Rawamangun No. 889', 'Pekalongan', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('dr. Amelia Hariyah', 'rahayuyessi@example.net', 'Gang Rungkut Industri No. 644', 'Cirebon', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('drg. Kuncara Gunarto, M.Ak', 'latifnainggolan@example.org', 'Jl. Cihampelas No. 3', 'Magelang', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('drg. Dewi Tamba, M.M.', 'purnawatisilvia@example.net', 'Gang Surapati No. 4', 'Tanjung Selor', 'Kalimantan Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Maimunah Mayasari', 'novimelani@example.net', 'Jl. Kebonjati No. 3', 'Palu', 'Sulawesi Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Jatmiko Mardhiyah', 'ani75@example.org', 'Jl. Moch. Toha No. 538', 'Pangkalpinang', 'Kepulauan Bangka Belitung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Saiful Pratama', 'waluyosafina@example.com', 'Jalan Jayawijaya No. 36', 'Palu', 'Sulawesi Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Puti Lestari', 'jamalialatupono@example.com', 'Jl. Cikutra Barat No. 696', 'Jambi', 'Jambi', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R.M. Cagak Saragih, M.Pd', 'wijayantiibun@example.org', 'Jl. Otto Iskandardinata No. 87', 'Sungai Penuh', 'Jambi', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R. Kuncara Sinaga, M.M.', 'zizi14@example.net', 'Jalan Antapani Lama No. 716', 'Jakarta', 'DKI Jakarta', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Drs. Gatot Nurdiyanti', 'npermata@example.com', 'Jl. Pasir Koja No. 66', 'Cirebon', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Farah Anggraini', 'qpermata@example.com', 'Jalan Asia Afrika No. 7', 'Magelang', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Yessi Halimah', 'ifirmansyah@example.org', 'Jl. Kutisari Selatan No. 0', 'Langsa', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Slamet Narpati, M.Farm', 'dabukkeraditya@example.net', 'Gg. Jayawijaya No. 47', 'Bandar Lampung', 'Lampung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Putri Farida', 'paris11@example.com', 'Gang Yos Sudarso No. 596', 'Tangerang', 'Banten', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Icha Melani', 'sakapradana@example.org', 'Jl. Kendalsari No. 5', 'Denpasar', 'Bali', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('H. Martaka Prayoga, S.E.I', 'yolandacengkir@example.com', 'Gang Sukajadi No. 3', 'Depok', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Suci Nababan', 'xnarpati@example.net', 'Gg. Tubagus Ismail No. 5', 'Palu', 'Sulawesi Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('drg. Diah Anggraini, S.Sos', 'dian95@example.com', 'Gang Monginsidi No. 40', 'Surabaya', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Najam Prakasa, S.IP', 'garda77@example.com', 'Jalan Jakarta No. 849', 'Bandar Lampung', 'Lampung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Langgeng Mandasari', 'ypurwanti@example.org', 'Jalan Rajawali Timur No. 81', 'Pekanbaru', 'Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Zahra Simanjuntak', 'xwijayanti@example.com', 'Jalan Laswi No. 34', 'Makassar', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R. Tasnim Firgantoro, S.IP', 'ebudiyanto@example.net', 'Jl. Antapani Lama No. 838', 'Surabaya', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Viman Simanjuntak', 'adhiarja71@example.net', 'Jalan Erlangga No. 92', 'Palangkaraya', 'Kalimantan Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Prakosa Mandala', 'simbolongaman@example.com', 'Gg. Pacuan Kuda No. 16', 'Palu', 'Sulawesi Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('dr. Dacin Dongoran, S.Farm', 'jwahyudin@example.net', 'Jl. Rungkut Industri No. 83', 'Ambon', 'Maluku', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ikhsan Widiastuti', 'aswanimardhiyah@example.net', 'Jl. Otto Iskandardinata No. 995', 'Surabaya', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Devi Permadi, M.M.', 'purwadiprasetyo@example.net', 'Gg. Peta No. 8', 'Pangkalpinang', 'Kepulauan Bangka Belitung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Cut Olivia Budiman', 'jokowijayanti@example.net', 'Jl. Pelajar Pejuang No. 0', 'Cirebon', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tgk. Kacung Saefullah', 'dindabudiman@example.net', 'Gang Ahmad Dahlan No. 4', 'Kediri', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Siti Nashiruddin', 'mahfud74@example.com', 'Gg. Monginsidi No. 592', 'Denpasar', 'Bali', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ajeng Prastuti', 'digdaya14@example.net', 'Gang Ir. H. Djuanda No. 4', 'Sabang', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tantri Kurniawan', 'irianautami@example.com', 'Jl. Abdul Muis No. 03', 'Mataram', 'Nusa Tenggara Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Cornelia Rajasa', 'rmulyani@example.org', 'Gang H.J Maemunah No. 7', 'Jakarta', 'DKI Jakarta', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gaiman Putra', 'pangeran15@example.com', 'Gg. Medokan Ayu No. 0', 'Manokwari', 'Papua Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dt. Gangsa Usada', 'widya55@example.com', 'Jalan Rajawali Timur No. 63', 'Salatiga', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gangsar Hariyah, M.Farm', 'mahdi31@example.org', 'Jalan R.E Martadinata No. 0', 'Dumai', 'Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Asmuni Natsir, M.Farm', 'agnesmayasari@example.net', 'Jalan Suniaraja No. 2', 'Singkawang', 'Kalimantan Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R. Shania Narpati', 'adikarawulandari@example.net', 'Jl. Kapten Muslihat No. 7', 'Kendari', 'Sulawesi Tenggara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Puji Kusmawati', 'nasab58@example.org', 'Gg. W.R. Supratman No. 38', 'Depok', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Akarsana Suartini, S.E.I', 'purwadisaragih@example.net', 'Jl. Pasteur No. 571', 'Batu', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (1, '+62 (76) 997 9846');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (1, '+62 (0402) 133-5112');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (2, '+62 (0180) 381 2792');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (2, '087 998 6933');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (3, '+62 (071) 379-4843');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (4, '+62-025-948-8939');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (4, '(079) 947-2608');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (4, '+62 (0097) 738 9228');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (5, '+62 (95) 765-8757');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (5, '(0269) 295 1067');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (6, '+62-0283-688-3966');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (6, '(017) 020-7892');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (6, '(0687) 606 1969');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (7, '088 508 7497');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (8, '+62 (0541) 695-9501');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (8, '+62 (0586) 332 7671');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (8, '+62 (0836) 887-7543');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (9, '(0885) 885-4691');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (9, '(014) 482-5323');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (9, '+62 (011) 660-5681');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (10, '+62 (910) 169-2103');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (11, '+62 (07) 030 0607');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (11, '+62 (089) 331-9433');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (11, '084 226 5281');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (12, '+62 (027) 658 2445');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (13, '+62 (0140) 622 9015');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (14, '+62 (290) 769-7465');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (14, '+62-0014-525-7951');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (15, '(0959) 907-9804');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (15, '(0475) 617-4520');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (16, '+62 (054) 740 6805');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (16, '+62-10-269-4111');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (17, '089 209 2813');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (17, '+62 (643) 014-8788');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (17, '+62 (0236) 294 3287');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (18, '+62 (0719) 474 3528');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (18, '+62 (82) 385-1023');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (19, '+62 (61) 464-5117');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (19, '0831161919');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (20, '+62-0516-124-5539');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (20, '+62 (0407) 410-1623');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (20, '+62 (44) 471 2414');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (21, '+62 (074) 950-6770');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (21, '0800450177');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (21, '+62 (85) 966 2022');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (22, '+62 (0328) 328 4520');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (22, '+62-462-705-3481');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (22, '(0613) 281-3098');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (23, '+62-0288-031-8900');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (23, '+62 (040) 036 9875');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (23, '+62 (063) 962-5860');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (24, '+62-064-275-4949');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (24, '(067) 230 8931');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (25, '+62 (50) 862-8768');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (26, '+62 (29) 261-0374');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (27, '+62 (363) 781 9406');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (28, '+62 (018) 476-7502');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (28, '+62 (0845) 666-2247');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (28, '+62 (102) 743 1163');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (29, '+62 (0057) 417-4825');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (29, '(0210) 741-3951');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (30, '+62 (17) 462-2923');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (30, '+62-97-957-9160');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (30, '(0844) 106 3298');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (31, '(0559) 323-0049');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (32, '+62 (052) 050-2411');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (32, '+62-47-283-5413');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (33, '(0810) 650 1166');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (34, '+62 (88) 487 5569');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (34, '(060) 293 0180');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (34, '+62 (049) 206-0072');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (35, '+62-02-143-4422');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (35, '+62 (099) 571-1368');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (35, '+62 (0588) 358 2890');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (36, '084 553 6991');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (37, '(000) 936-8589');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (38, '(037) 113 0675');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (38, '+62 (04) 949 5025');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (39, '+62 (708) 363-9596');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (39, '080 757 1561');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (40, '+62 (047) 312 8228');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (41, '+62 (75) 442 0032');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (42, '+62-57-243-0853');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (43, '(000) 439-9380');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (44, '(002) 633 9687');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (44, '+62-048-201-4320');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (45, '082 858 9932');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (45, '+62 (47) 853 7839');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (46, '(0436) 513 0055');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (46, '+62 (18) 969-1134');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (47, '+62 (034) 415 4176');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (48, '+62 (0097) 858 1595');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (49, '+62 (088) 332-1965');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (50, '+62-0023-395-2114');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (50, '+62 (0920) 829-9811');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (51, '+62 (74) 008 9078');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (52, '0813272275');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (53, '+62 (41) 079-0497');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (54, '+62-91-142-5373');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (55, '+62-057-020-9792');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (56, '+62-546-512-0646');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (56, '+62-088-334-9550');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (56, '+62 (21) 178-8962');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (57, '+62 (121) 071-3976');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (58, '(093) 445 0411');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (58, '(020) 261-1818');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (58, '084 446 0831');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (59, '+62 (060) 776 9555');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (59, '+62 (38) 247-2562');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (59, '(0942) 670 4713');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (60, '+62 (600) 377-5154');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (60, '+62 (86) 156-2847');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (61, '+62 (027) 548-4807');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (61, '(0112) 706-7534');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (62, '+62 (0021) 493 0033');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (63, '+62 (94) 395-2819');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (63, '+62 (0676) 128 5991');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (64, '+62 (0196) 430 9275');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (64, '(009) 081 8674');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (65, '+62 (0586) 267 0217');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (65, '+62 (0592) 509-4696');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (65, '+62 (0388) 154-5720');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (66, '+62 (0397) 163 8193');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (67, '(0238) 774-3190');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (67, '+62 (202) 683 3119');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (67, '(073) 285-1954');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (68, '+62-007-855-4185');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (68, '(0609) 090 8847');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (69, '+62-0455-556-5250');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (69, '(0766) 916 7813');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (69, '+62 (0406) 935-1643');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (70, '(033) 604-1765');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (71, '+62-036-769-1125');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (71, '+62 (049) 747-1151');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (72, '+62 (633) 510-1092');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (73, '+62 (0333) 863-2631');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (73, '+62-33-983-2731');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (73, '(0569) 699-1280');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (74, '+62-989-212-9527');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (74, '+62 (38) 708-6766');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (74, '+62 (0910) 564 4567');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (75, '0818417666');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (76, '+62-047-527-8056');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (77, '+62 (0540) 558-0635');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (77, '+62 (689) 657-2735');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (77, '(061) 442 5176');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (78, '+62-0373-861-5930');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (78, '(0405) 823-9775');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (79, '+62 (042) 705 5425');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (79, '+62 (853) 036-1092');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (79, '+62-095-221-0279');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (80, '+62 (0436) 650-0507');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (80, '(0898) 230 2670');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (80, '(0274) 093 4638');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (81, '+62 (005) 319-9159');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (81, '+62 (0634) 320 4674');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (82, '+62-064-743-1935');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (82, '088 266 8950');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (82, '+62 (0545) 336 6165');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (83, '(0110) 032 3369');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (83, '+62-82-697-2242');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (83, '+62-0436-724-8985');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (84, '+62 (0480) 749 6770');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (85, '+62-0626-355-5193');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (85, '+62-062-407-6889');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (85, '+62 (0539) 907-5790');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (86, '+62 (64) 440-5998');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (86, '(0461) 863 1545');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (86, '+62 (982) 014-7435');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (87, '+62 (035) 496 8879');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (87, '+62 (032) 722-1687');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (88, '+62-0099-572-9688');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (89, '+62 (361) 383 8779');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (90, '+62 (0430) 333 1961');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (90, '+62 (44) 537-3340');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (91, '(0275) 388 2625');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (91, '+62 (96) 823-7694');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (92, '+62 (093) 665-4867');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (92, '+62 (0250) 925-1373');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (93, '+62 (0607) 158 1955');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (94, '+62 (892) 728 8358');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (94, '+62 (73) 378 7087');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (94, '+62-0893-462-1149');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (95, '+62 (0965) 257-2689');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (95, '+62-680-645-7079');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (95, '(0772) 740 1979');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (96, '+62-061-440-4496');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (96, '+62 (478) 758 0561');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (96, '+62 (86) 575 7894');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (97, '+62 (03) 705-4529');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (98, '+62 (057) 882 4245');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (98, '(049) 783-8272');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (98, '+62 (308) 704 4985');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (99, '083 991 2948');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (99, '+62 (832) 572-0249');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (100, '+62-0820-631-1664');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (100, '+62 (153) 042 7292');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (100, '(0304) 230 3209');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (101, '(0784) 230-2211');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (101, '+62 (067) 106-5948');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (101, '+62-060-996-8222');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (102, '+62 (009) 675-2258');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (102, '+62-0216-114-3730');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (102, '(093) 764 7719');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (103, '+62-0352-192-1310');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (103, '(063) 080-7879');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (104, '(0704) 005-1428');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (104, '089 154 6596');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (105, '+62 (086) 353-0494');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (105, '(023) 404 5146');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (106, '087 090 0939');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (106, '086 851 0275');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (107, '(0541) 795 7529');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (107, '+62 (643) 240 0653');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (108, '(0094) 335-6151');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (108, '+62 (001) 297 8839');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (108, '+62-034-087-9360');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (109, '+62 (041) 756-3432');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (109, '0852818763');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (110, '0802933143');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (111, '+62 (0465) 135 7328');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (112, '+62 (444) 239-1617');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (112, '(0381) 704 5387');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (113, '+62 (044) 085 4999');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (113, '0853723971');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (113, '+62 (021) 829 6688');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (114, '+62-64-650-2536');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (115, '+62 (017) 269-7972');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (115, '0872681030');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (116, '+62-200-926-1949');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (116, '(0045) 445-9417');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (117, '(030) 509 5453');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (117, '+62 (93) 432 0417');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (118, '(007) 748-3307');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (118, '(056) 828 1346');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (119, '+62 (016) 719 8364');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (119, '+62 (041) 825 5866');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (120, '+62-264-079-8450');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (120, '+62 (099) 453 1105');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (121, '+62-0702-758-1098');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (121, '+62 (401) 781-2299');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (121, '+62-88-256-4861');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (122, '+62 (046) 398-4353');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (122, '+62-200-107-0614');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (123, '(0807) 274-3424');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (123, '+62-0629-734-4685');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (123, '+62 (392) 579-1421');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (124, '+62 (0490) 096-3326');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (124, '(0238) 404 3058');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (125, '084 474 1746');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (125, '+62 (023) 937-6774');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (126, '+62-503-736-3901');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (126, '+62-224-418-5119');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (127, '+62 (594) 068 3577');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (127, '087 059 6423');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (127, '+62 (912) 405-3423');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (128, '(025) 495-1352');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (128, '+62-454-130-1214');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (128, '(0340) 055-9137');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (129, '+62-0648-680-4016');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (129, '+62-28-295-1831');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (129, '+62 (064) 664-5739');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (130, '+62-843-138-9561');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (131, '+62 (023) 329-9515');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (132, '+62 (04) 710-9982');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (132, '+62 (848) 990 5330');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (132, '(0548) 322 9574');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (133, '080 821 6427');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (133, '+62 (04) 951 4302');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (134, '(063) 335-9300');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (135, '+62 (0188) 684 6576');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (135, '0872391100');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (135, '+62 (0564) 346 9858');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (136, '(001) 629 7807');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (137, '+62 (255) 006 4848');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (137, '+62 (0903) 531-6949');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (138, '+62 (614) 944 1265');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (138, '0850094584');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (138, '+62-87-420-8904');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (139, '+62 (88) 536 8954');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (139, '(0562) 280 5270');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (139, '0892682386');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (140, '+62-0110-818-5320');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (140, '(0803) 804 0661');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (140, '+62 (0195) 653-8137');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (141, '+62 (009) 905 6861');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (141, '+62-69-277-7124');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (142, '+62 (523) 491 6029');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (143, '+62 (0992) 000-7014');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (143, '+62 (014) 009 9502');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (143, '+62-43-076-9884');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (144, '0811956085');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (145, '+62 (08) 831 3887');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (145, '(095) 672-0617');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (145, '+62 (162) 377 0441');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (146, '+62-089-796-8539');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (146, '0867302826');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (147, '(052) 569-5352');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (148, '+62-0169-281-8347');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (149, '+62-403-175-8360');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (149, '+62 (75) 270-5458');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (149, '+62 (0615) 528-8261');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (150, '(0082) 712-7021');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (150, '(097) 105 4673');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (151, '+62 (79) 943 8669');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (151, '+62 (0166) 950-3413');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (152, '(0818) 139-3255');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (152, '+62 (07) 025 2899');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (152, '+62-0122-888-3425');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (153, '0872675098');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (153, '(0963) 548 4615');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (154, '(034) 636-7109');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (155, '+62-0502-634-3277');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (155, '+62-0897-348-7909');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (156, '+62 (00) 710-8169');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (156, '+62 (092) 664-6275');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (157, '+62 (0804) 086 2783');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (157, '+62-894-276-4539');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (158, '+62-0295-568-8847');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (159, '+62 (011) 114-5438');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (159, '+62 (60) 440-0910');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (160, '(0697) 523-2045');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (161, '(0966) 390 8772');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (161, '0812644631');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (162, '+62-94-489-2268');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (162, '+62 (0508) 581-5415');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (163, '+62 (07) 024 8236');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (163, '+62 (042) 842-8611');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (164, '+62 (361) 566 3491');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (164, '(0593) 008 9953');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (164, '+62 (014) 537-2116');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (165, '(011) 601-5583');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (165, '(045) 788 3438');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (166, '+62-08-151-8464');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (166, '081 116 0333');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (166, '085 863 5495');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (167, '(0722) 714-6830');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (167, '086 721 9436');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (167, '+62 (031) 443 1287');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (168, '0886439595');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (168, '+62 (29) 121-2057');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (168, '0864212960');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (169, '+62 (63) 983-6744');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (169, '+62 (095) 207 4884');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (170, '+62-91-999-6068');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (171, '+62 (15) 255-4505');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (171, '+62 (83) 795 4566');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (171, '(0588) 030-0843');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (172, '+62 (74) 089-1901');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (172, '+62-0966-880-8597');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (172, '(0425) 559 0873');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (173, '+62-038-559-4014');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (173, '+62-0765-019-6578');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (173, '+62 (986) 598 6286');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (174, '(020) 578 6774');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (174, '(0542) 328-2464');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (174, '083 990 5898');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (175, '+62 (850) 518 5600');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (175, '+62 (765) 816-1354');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (175, '086 296 4835');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (176, '+62 (027) 916 8113');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (176, '(0045) 872 6435');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (176, '+62-914-885-0364');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (177, '+62 (0322) 673-6691');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (177, '+62 (0515) 438 2212');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (178, '(0938) 813 6155');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (178, '+62-65-975-2299');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (179, '+62-049-952-7844');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (179, '+62-0034-528-7883');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (180, '+62-98-268-9248');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (180, '+62-0309-760-1048');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (180, '+62 (0737) 478-4674');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (181, '+62 (035) 547-6486');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (181, '+62 (0537) 157 0499');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (182, '(0751) 489 6951');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (182, '+62 (0233) 101-8934');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (183, '+62 (06) 605 1364');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (183, '+62 (291) 378 3506');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (184, '+62 (97) 486 6525');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (185, '(0916) 951 7680');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (185, '(0515) 226 7109');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (186, '+62-112-467-4997');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (186, '+62-181-096-6450');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (186, '+62 (388) 722-3698');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (187, '+62 (913) 555-5935');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (188, '+62 (518) 938 8967');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (188, '+62 (92) 629 1828');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (189, '+62 (04) 189 7894');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (190, '+62 (76) 558-7274');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (191, '+62 (0674) 297-2565');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (191, '+62 (0458) 301 3101');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (192, '(070) 365-9994');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (193, '(0095) 942-4361');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (193, '+62 (0325) 728-7586');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (194, '+62 (0986) 423-4797');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (195, '+62-83-205-2120');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (195, '+62-80-987-9964');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (196, '+62 (498) 516 0461');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (196, '0803371120');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (197, '(038) 839-4913');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (197, '+62 (540) 699 8497');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (198, '+62 (0045) 230 9602');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (198, '+62-49-223-0342');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (199, '+62 (069) 907 8271');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (200, '+62 (42) 533-8498');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (200, '+62 (281) 493-7146');
