-- adopter
INSERT INTO adopter (id_user, preferensi) VALUES (101, 'Hewan eksotis');
INSERT INTO adopter (id_user, preferensi) VALUES (102, 'Hewan ras');
INSERT INTO adopter (id_user, preferensi) VALUES (103, 'Reptil');
INSERT INTO adopter (id_user, preferensi) VALUES (104, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (105, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (106, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (107, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (108, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (109, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (110, 'Hewan eksotis');
INSERT INTO adopter (id_user, preferensi) VALUES (111, 'Hewan ras');
INSERT INTO adopter (id_user, preferensi) VALUES (112, 'Kucing');
INSERT INTO adopter (id_user, preferensi) VALUES (113, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (114, 'Hewan ras');
INSERT INTO adopter (id_user, preferensi) VALUES (115, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (116, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (117, 'Anjing besar');
INSERT INTO adopter (id_user, preferensi) VALUES (118, 'Hewan tidak berbulu');
INSERT INTO adopter (id_user, preferensi) VALUES (119, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (120, 'Kucing');
INSERT INTO adopter (id_user, preferensi) VALUES (121, 'Unggas');
INSERT INTO adopter (id_user, preferensi) VALUES (122, 'Hewan tidak berbulu');
INSERT INTO adopter (id_user, preferensi) VALUES (123, 'Anjing kecil');
INSERT INTO adopter (id_user, preferensi) VALUES (124, 'Hewan ras');
INSERT INTO adopter (id_user, preferensi) VALUES (125, 'Anjing kecil');
INSERT INTO adopter (id_user, preferensi) VALUES (126, 'Kucing');
INSERT INTO adopter (id_user, preferensi) VALUES (127, 'Hewan ras');
INSERT INTO adopter (id_user, preferensi) VALUES (128, 'Anjing kecil');
INSERT INTO adopter (id_user, preferensi) VALUES (129, 'Kucing');
INSERT INTO adopter (id_user, preferensi) VALUES (130, 'Reptil');
INSERT INTO adopter (id_user, preferensi) VALUES (131, 'Hewan tidak berbulu');
INSERT INTO adopter (id_user, preferensi) VALUES (132, 'Hewan tidak berbulu');
INSERT INTO adopter (id_user, preferensi) VALUES (133, 'Anjing kecil');
INSERT INTO adopter (id_user, preferensi) VALUES (134, 'Hewan ras');
INSERT INTO adopter (id_user, preferensi) VALUES (135, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (136, 'Anjing kecil');
INSERT INTO adopter (id_user, preferensi) VALUES (137, 'Anjing besar');
INSERT INTO adopter (id_user, preferensi) VALUES (138, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (139, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (140, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (141, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (142, 'Kucing');
INSERT INTO adopter (id_user, preferensi) VALUES (143, 'Hewan eksotis');
INSERT INTO adopter (id_user, preferensi) VALUES (144, 'Hewan eksotis');
INSERT INTO adopter (id_user, preferensi) VALUES (145, 'Unggas');
INSERT INTO adopter (id_user, preferensi) VALUES (146, 'Hewan tidak berbulu');
INSERT INTO adopter (id_user, preferensi) VALUES (147, 'Hewan eksotis');
INSERT INTO adopter (id_user, preferensi) VALUES (148, 'Anjing kecil');
INSERT INTO adopter (id_user, preferensi) VALUES (149, 'Hewan tidak berbulu');
INSERT INTO adopter (id_user, preferensi) VALUES (150, 'Kucing');
INSERT INTO adopter (id_user, preferensi) VALUES (151, 'Anjing besar');
INSERT INTO adopter (id_user, preferensi) VALUES (152, 'Hewan ras');
INSERT INTO adopter (id_user, preferensi) VALUES (153, 'Kucing');
INSERT INTO adopter (id_user, preferensi) VALUES (154, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (155, 'Hewan ras');
INSERT INTO adopter (id_user, preferensi) VALUES (156, 'Hewan eksotis');
INSERT INTO adopter (id_user, preferensi) VALUES (157, 'Hewan eksotis');
INSERT INTO adopter (id_user, preferensi) VALUES (158, 'Hewan eksotis');
INSERT INTO adopter (id_user, preferensi) VALUES (159, 'Hewan eksotis');
INSERT INTO adopter (id_user, preferensi) VALUES (160, 'Unggas');
INSERT INTO adopter (id_user, preferensi) VALUES (161, 'Hewan tidak berbulu');
INSERT INTO adopter (id_user, preferensi) VALUES (162, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (163, 'Reptil');
INSERT INTO adopter (id_user, preferensi) VALUES (164, 'Reptil');
INSERT INTO adopter (id_user, preferensi) VALUES (165, 'Hewan ras');
INSERT INTO adopter (id_user, preferensi) VALUES (166, 'Anjing besar');
INSERT INTO adopter (id_user, preferensi) VALUES (167, 'Kucing');
INSERT INTO adopter (id_user, preferensi) VALUES (168, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (169, 'Hewan tidak berbulu');
INSERT INTO adopter (id_user, preferensi) VALUES (170, 'Hewan tidak berbulu');
INSERT INTO adopter (id_user, preferensi) VALUES (171, 'Kucing');
INSERT INTO adopter (id_user, preferensi) VALUES (172, 'Hewan eksotis');
INSERT INTO adopter (id_user, preferensi) VALUES (173, 'Anjing kecil');
INSERT INTO adopter (id_user, preferensi) VALUES (174, 'Unggas');
INSERT INTO adopter (id_user, preferensi) VALUES (175, 'Anjing kecil');
INSERT INTO adopter (id_user, preferensi) VALUES (176, 'Anjing besar');
INSERT INTO adopter (id_user, preferensi) VALUES (177, 'Anjing besar');
INSERT INTO adopter (id_user, preferensi) VALUES (178, 'Anjing kecil');
INSERT INTO adopter (id_user, preferensi) VALUES (179, 'Unggas');
INSERT INTO adopter (id_user, preferensi) VALUES (180, 'Anjing besar');
INSERT INTO adopter (id_user, preferensi) VALUES (181, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (182, 'Anjing besar');
INSERT INTO adopter (id_user, preferensi) VALUES (183, 'Anjing besar');
INSERT INTO adopter (id_user, preferensi) VALUES (184, 'Hewan ras');
INSERT INTO adopter (id_user, preferensi) VALUES (185, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (186, 'Hewan tidak berbulu');
INSERT INTO adopter (id_user, preferensi) VALUES (187, 'Kucing');
INSERT INTO adopter (id_user, preferensi) VALUES (188, 'Kucing');
INSERT INTO adopter (id_user, preferensi) VALUES (189, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (190, 'Hewan ras');
INSERT INTO adopter (id_user, preferensi) VALUES (191, NULL);
INSERT INTO adopter (id_user, preferensi) VALUES (192, 'Kucing');
INSERT INTO adopter (id_user, preferensi) VALUES (193, 'Reptil');
INSERT INTO adopter (id_user, preferensi) VALUES (194, 'Anjing besar');
INSERT INTO adopter (id_user, preferensi) VALUES (195, 'Unggas');
INSERT INTO adopter (id_user, preferensi) VALUES (196, 'Reptil');
INSERT INTO adopter (id_user, preferensi) VALUES (197, 'Hewan eksotis');
INSERT INTO adopter (id_user, preferensi) VALUES (198, 'Reptil');
INSERT INTO adopter (id_user, preferensi) VALUES (199, 'Unggas');
INSERT INTO adopter (id_user, preferensi) VALUES (200, 'Unggas');
