INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dacin Halimah', 'ypuspita@example.com', 'Gang Pacuan Kuda No. 04', 'Bekasi', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tgk. Endah Uyainah, M.Farm', 'dzulkarnain@example.net', 'Jl. BKR No. 7', 'Sukabumi', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Syahrini Padmasari', 'lailawacana@example.com', 'Gg. Ronggowarsito No. 493', 'Yogyakarta', 'DI Yogyakarta', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R.M. Warji Maulana', 'tarihoranprayogo@example.com', 'Jl. S. Parman No. 041', 'Tarakan', 'Kalimantan Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Kamaria Saptono', 'dwahyudin@example.org', 'Jl. Rajiman No. 540', 'Blitar', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Maya Wijayanti', 'lbudiman@example.net', 'Gg. Monginsidi No. 1', 'Tangerang', 'Banten', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Lukman Kuswoyo, S.IP', 'qlaksita@example.org', 'Jalan W.R. Supratman No. 511', 'Tasikmalaya', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Kajen Marbun', 'tyuniar@example.org', 'Jl. Laswi No. 283', 'Bekasi', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Drajat Nashiruddin', 'oskar49@example.com', 'Gg. Kendalsari No. 33', 'Mojokerto', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gasti Firmansyah', 'xutama@example.net', 'Jl. Jend. Sudirman No. 0', 'Mojokerto', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Oskar Pranowo', 'laksmiwatiellis@example.net', 'Jl. Erlangga No. 223', 'Padang', 'Sumatera Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Setya Padmasari', 'clarasihombing@example.org', 'Jl. Monginsidi No. 20', 'Sukabumi', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('dr. Mala Permata, S.Kom', 'pangestuhadi@example.com', 'Jl. Moch. Toha No. 42', 'Jakarta', 'DKI Jakarta', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Jail Pratama', 'hastutibakiadi@example.net', 'Gang M.H Thamrin No. 45', 'Semarang', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Mulyanto Pertiwi', 'faridayani@example.org', 'Gang Indragiri No. 0', 'Palembang', 'Sumatera Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tugiman Rahayu', 'ika70@example.org', 'Jalan HOS. Cokroaminoto No. 09', 'Ambon', 'Maluku', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ilsa Farida', 'gpradipta@example.org', 'Jalan Dr. Djunjunan No. 38', 'Gorontalo', 'Gorontalo', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dariati Permadi', 'rahayukayun@example.org', 'Gg. H.J Maemunah No. 45', 'Bekasi', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tgk. Jaya Saragih', 'viman78@example.net', 'Gang Kutai No. 627', 'Jambi', 'Jambi', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Shakila Saptono', 'artawanprakasa@example.com', 'Gg. Gegerkalong Hilir No. 81', 'Bogor', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Paiman Kusmawati', 'danang15@example.com', 'Jalan Raya Ujungberung No. 3', 'Bandar Lampung', 'Lampung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Cut Elisa Riyanti, M.Ak', 'upiknuraini@example.net', 'Jalan Kapten Muslihat No. 86', 'Tanjung Selor', 'Kalimantan Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dr. Lidya Firmansyah, M.M.', 'simbolonjasmani@example.net', 'Jalan Kapten Muslihat No. 97', 'Tanjung Selor', 'Kalimantan Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Wirda Widodo', 'cahyantodamanik@example.com', 'Jalan Suryakencana No. 66', 'Mojokerto', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Yusuf Mustofa', 'yuniarhasan@example.net', 'Jl. Cempaka No. 53', 'Bengkulu', 'Bengkulu', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Paris Saragih', 'wandriani@example.org', 'Jl. Cikapayang No. 254', 'Magelang', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dirja Hutapea', 'cdamanik@example.net', 'Jl. Gedebage Selatan No. 72', 'Banda Aceh', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Latika Nababan', 'balamantri80@example.com', 'Jalan Otto Iskandardinata No. 042', 'Metro', 'Lampung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Safina Nainggolan', 'surya76@example.net', 'Jl. Waringin No. 2', 'Bontang', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Cawisono Mardhiyah', 'hakimmahdi@example.org', 'Gang Cikutra Timur No. 15', 'Yogyakarta', 'DI Yogyakarta', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ir. Wulan Sudiati, S.H.', 'tarisetiawan@example.net', 'Jl. Dipenogoro No. 066', 'Purwokerto', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('H. Galang Lazuardi, S.Sos', 'lasmanto47@example.net', 'Jalan Lembong No. 9', 'Tarakan', 'Kalimantan Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Laksana Pradana', 'suryonocawisono@example.net', 'Gang H.J Maemunah No. 57', 'Semarang', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Eka Dabukke, S.Gz', 'prakosa54@example.com', 'Jalan Sentot Alibasa No. 482', 'Binjai', 'Sumatera Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Lutfan Andriani', 'surya61@example.com', 'Gang Soekarno Hatta No. 38', 'Bandar Lampung', 'Lampung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R. Gandewa Pertiwi, S.E.', 'puspasarijindra@example.com', 'Jalan Stasiun Wonokromo No. 86', 'Kendari', 'Sulawesi Tenggara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Puti Jamalia Siregar', 'hastutirika@example.com', 'Jalan Kendalsari No. 914', 'Cirebon', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dr. Hamima Hakim, S.Pd', 'shakilaanggriawan@example.com', 'Gg. Sukabumi No. 9', 'Malang', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Oni Maulana, S.E.I', 'gambiranurdiyanti@example.org', 'Jalan Pacuan Kuda No. 0', 'Surabaya', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Amalia Salahudin', 'dwaluyo@example.net', 'Jalan Raya Setiabudhi No. 99', 'Sukabumi', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Puti Maheswara', 'natsirfitriani@example.com', 'Jl. Kendalsari No. 5', 'Sabang', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ina Sirait', 'kemalmayasari@example.org', 'Jalan PHH. Mustofa No. 9', 'Palopo', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Edison Suartini', 'putusiregar@example.net', 'Jalan Jend. A. Yani No. 8', 'Kupang', 'Nusa Tenggara Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Baktiono Budiman', 'gambira43@example.net', 'Jalan Ahmad Dahlan No. 44', 'Tanjungpinang', 'Kepulauan Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Asmadi Simbolon', 'samosirlatika@example.org', 'Gang Kiaracondong No. 92', 'Batu', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Cahyadi Hartati', 'utamafirmansyah@example.org', 'Jalan Cikutra Timur No. 9', 'Pangkalpinang', 'Kepulauan Bangka Belitung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Padmi Pratama', 'kiandrasitompul@example.com', 'Gang Joyoboyo No. 17', 'Singkawang', 'Kalimantan Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Panji Jailani', 'elvinalailasari@example.com', 'Gg. Moch. Ramdan No. 194', 'Bitung', 'Sulawesi Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Zizi Widiastuti', 'jabal18@example.org', 'Jalan Merdeka No. 677', 'Parepare', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Irfan Yuniar', 'eadriansyah@example.com', 'Gang Cikutra Timur No. 67', 'Pekanbaru', 'Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tgk. Paulin Budiman, S.Kom', 'nnatsir@example.com', 'Gang Rawamangun No. 9', 'Binjai', 'Sumatera Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dono Nababan, S.IP', 'violetsetiawan@example.org', 'Gang H.J Maemunah No. 07', 'Pontianak', 'Kalimantan Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Intan Simbolon', 'cagakpratama@example.com', 'Jalan Rajawali Barat No. 74', 'Denpasar', 'Bali', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Usyi Kurniawan', 'melanitantri@example.com', 'Gang Pasteur No. 089', 'Batam', 'Kepulauan Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Aisyah Mardhiyah', 'dartono09@example.com', 'Jl. Jend. Sudirman No. 3', 'Sungai Penuh', 'Jambi', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tgk. Daniswara Nashiruddin, S.Pd', 'wacanagadang@example.net', 'Gang Merdeka No. 179', 'Bukittinggi', 'Sumatera Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Padmi Hidayat', 'wulandarijaya@example.net', 'Jalan Suryakencana No. 704', 'Ternate', 'Maluku Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Adika Anggraini', 'ajimansusanti@example.net', 'Jalan M.T Haryono No. 196', 'Bukittinggi', 'Sumatera Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Winda Ramadan', 'wage49@example.net', 'Jl. Sentot Alibasa No. 426', 'Balikpapan', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Alika Waluyo', 'agnes75@example.net', 'Jl. Cihampelas No. 942', 'Bontang', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Garda Pradipta', 'esaptono@example.org', 'Gg. Joyoboyo No. 63', 'Batam', 'Kepulauan Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Hadi Mangunsong', 'salmanharyanti@example.org', 'Jl. Gedebage Selatan No. 8', 'Palopo', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R.A. Nabila Hassanah', 'isudiati@example.net', 'Gg. Tubagus Ismail No. 6', 'Kediri', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Devi Rahmawati', 'pranawa38@example.org', 'Jalan Kiaracondong No. 881', 'Mojokerto', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Olivia Nashiruddin', 'mangunsongirma@example.net', 'Jl. Bangka Raya No. 44', 'Tidore', 'Maluku Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Vanya Firgantoro', 'utamiartawan@example.net', 'Jalan Tubagus Ismail No. 601', 'Pekanbaru', 'Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ega Mangunsong', 'jamaliaramadan@example.org', 'Gg. PHH. Mustofa No. 2', 'Bekasi', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Faizah Saefullah', 'dagel98@example.com', 'Gg. Erlangga No. 42', 'Tasikmalaya', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Perkasa Wijayanti', 'karsa64@example.org', 'Gg. Kiaracondong No. 2', 'Tidore', 'Maluku Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Vero Halimah', 'ekalaksita@example.com', 'Gang Rumah Sakit No. 80', 'Ternate', 'Maluku Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dr. Uchita Januar, S.Psi', 'salmanmaryati@example.net', 'Jalan Peta No. 9', 'Pangkalpinang', 'Kepulauan Bangka Belitung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('dr. Syahrini Iswahyudi', 'handayaniluis@example.com', 'Jalan R.E Martadinata No. 845', 'Bontang', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dr. Rahmi Laksmiwati', 'nyolanda@example.net', 'Gang Ir. H. Djuanda No. 222', 'Padang', 'Sumatera Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Bakiadi Astuti', 'rharyanti@example.com', 'Jl. Jamika No. 8', 'Solo', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Michelle Mangunsong, S.Pt', 'balijan51@example.com', 'Gang Sadang Serang No. 902', 'Gorontalo', 'Gorontalo', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Xanana Purnawati, M.M.', 'yuliartiyani@example.org', 'Gg. Ciwastra No. 8', 'Pekalongan', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dt. Rangga Hariyah', 'fwinarno@example.org', 'Gg. BKR No. 752', 'Tegal', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Zaenab Mardhiyah', 'randriani@example.org', 'Gg. Rajiman No. 02', 'Lhokseumawe', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ir. Restu Farida, M.Ak', 'winarsihharjo@example.org', 'Jalan Rajawali Barat No. 67', 'Gorontalo', 'Gorontalo', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Kania Mahendra', 'lrahmawati@example.net', 'Gg. Astana Anyar No. 1', 'Sorong', 'Papua Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ir. Panca Hidayanto, S.T.', 'mahesamulyani@example.net', 'Jl. Ciumbuleuit No. 28', 'Kupang', 'Nusa Tenggara Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R.A. Endah Wijaya', 'santosogangsa@example.com', 'Gang Gardujati No. 123', 'Jakarta', 'DKI Jakarta', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Jaswadi Pratama', 'naradipratama@example.org', 'Gang Tubagus Ismail No. 97', 'Semarang', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Betania Wulandari', 'sihombingbakidin@example.com', 'Jl. Jend. Sudirman No. 8', 'Sukabumi', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Zelaya Mangunsong', 'pratamaanggabaya@example.com', 'Jalan Kebonjati No. 75', 'Metro', 'Lampung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Rahayu Simanjuntak', 'yolandawage@example.org', 'Jl. Rumah Sakit No. 726', 'Lhokseumawe', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('KH. Cecep Widodo, S.H.', 'cawisadiastuti@example.com', 'Gg. Cikapayang No. 184', 'Dumai', 'Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Elma Novitasari', 'respati09@example.net', 'Jalan Dr. Djunjunan No. 9', 'Mamuju', 'Sulawesi Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Yono Wijaya', 'ghalimah@example.com', 'Jl. Soekarno Hatta No. 0', 'Metro', 'Lampung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Bakiman Januar', 'wawan08@example.com', 'Gg. Moch. Ramdan No. 28', 'Singkawang', 'Kalimantan Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Vino Prayoga, S.Pd', 'ibun91@example.com', 'Jl. Cihampelas No. 699', 'Tarakan', 'Kalimantan Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Jagapati Wijayanti', 'laksitaendra@example.org', 'Gg. Wonoayu No. 5', 'Serang', 'Banten', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ir. Nrima Najmudin, S.E.I', 'restususanti@example.net', 'Gang Otto Iskandardinata No. 83', 'Tidore', 'Maluku Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Edi Yuniar', 'hidayantojindra@example.net', 'Gg. Stasiun Wonokromo No. 454', 'Bitung', 'Sulawesi Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Nasab Purnawati', 'dadiprasetya@example.net', 'Gang Pasteur No. 40', 'Tegal', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Emin Jailani', 'kamal63@example.com', 'Jl. Moch. Ramdan No. 67', 'Cirebon', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Drs. Aisyah Suwarno, S.Ked', 'tambaraihan@example.com', 'Jl. Joyoboyo No. 9', 'Kendari', 'Sulawesi Tenggara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Luwes Fujiati', 'mangunsongsimon@example.com', 'Gg. Laswi No. 73', 'Surabaya', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Soleh Prastuti, S.T.', 'adhiarjahalimah@example.com', 'Jl. Pelajar Pejuang No. 50', 'Kediri', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Shakila Zulkarnain', 'mahdiwijayanti@example.net', 'Gg. Jayawijaya No. 835', 'Malang', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ozy Gunarto', 'nurdiyantimanah@example.net', 'Jl. Sentot Alibasa No. 779', 'Langsa', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Kiandra Rajasa', 'damusetiawan@example.com', 'Jl. Suniaraja No. 1', 'Binjai', 'Sumatera Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Usyi Widiastuti', 'qhakim@example.net', 'Jalan Rajawali Timur No. 29', 'Depok', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tgk. Limar Hardiansyah', 'julirahmawati@example.org', 'Jl. KH Amin Jasuta No. 6', 'Sungai Penuh', 'Jambi', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Oman Salahudin, M.M.', 'siskaanggriawan@example.net', 'Jalan Rumah Sakit No. 805', 'Salatiga', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('dr. Belinda Suryatmi', 'asmiantousada@example.org', 'Gg. Gedebage Selatan No. 342', 'Bontang', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R.A. Shania Haryanto, S.T.', 'saifulhutapea@example.com', 'Gang Rajiman No. 537', 'Serang', 'Banten', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Kenes Hardiansyah', 'vera64@example.org', 'Gang Sentot Alibasa No. 0', 'Bandar Lampung', 'Lampung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Jono Wastuti', 'iswahyudimulya@example.org', 'Jl. Waringin No. 6', 'Pangkalpinang', 'Kepulauan Bangka Belitung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tgk. Margana Kurniawan', 'hasta23@example.net', 'Gang KH Amin Jasuta No. 82', 'Mamuju', 'Sulawesi Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ratna Hutapea', 'gprayoga@example.org', 'Gg. Medokan Ayu No. 834', 'Solo', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Lantar Purnawati', 'fpudjiastuti@example.org', 'Jalan Cempaka No. 84', 'Sungai Penuh', 'Jambi', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Jasmin Yulianti', 'indahgunarto@example.org', 'Gang Moch. Ramdan No. 75', 'Bitung', 'Sulawesi Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R. Rina Winarno', 'gandaardianto@example.com', 'Gang Merdeka No. 77', 'Parepare', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tgk. Omar Wacana', 'bhalim@example.org', 'Gg. Astana Anyar No. 595', 'Salatiga', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ella Ramadan', 'saefullahdodo@example.net', 'Gg. Tebet Barat Dalam No. 373', 'Mamuju', 'Sulawesi Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Vera Suryatmi', 'wijayantiajeng@example.net', 'Gang Antapani Lama No. 3', 'Makassar', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gamanto Agustina', 'bakionozulaika@example.org', 'Jalan Rajawali Timur No. 87', 'Tidore', 'Maluku Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Purwa Wahyuni', 'paramitahidayanto@example.org', 'Gang Surapati No. 668', 'Sorong', 'Papua Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Paramita Saptono', 'adriansyahbalapati@example.com', 'Gg. Kutai No. 38', 'Sorong', 'Papua Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Drs. Aswani Hardiansyah', 'radit88@example.net', 'Gang Raya Setiabudhi No. 7', 'Banjarmasin', 'Kalimantan Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('T. Endra Saefullah, M.M.', 'estiawansinaga@example.org', 'Jalan S. Parman No. 689', 'Lhokseumawe', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tgk. Makara Thamrin', 'galang48@example.com', 'Gg. Jend. Sudirman No. 30', 'Tanjung Selor', 'Kalimantan Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tira Pangestu', 'sitorusade@example.org', 'Jl. M.T Haryono No. 8', 'Sofifi', 'Maluku Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Safina Anggraini', 'rastuti@example.org', 'Jl. Surapati No. 27', 'Mataram', 'Nusa Tenggara Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Najib Sihombing', 'tri77@example.org', 'Jalan Kiaracondong No. 13', 'Ternate', 'Maluku Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Puti Samiah Wijayanti', 'nurdiyantisaiful@example.net', 'Jalan Cihampelas No. 974', 'Samarinda', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('drg. Genta Prasetyo', 'yuliantiaslijan@example.org', 'Gg. KH Amin Jasuta No. 0', 'Sofifi', 'Maluku Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Kezia Farida', 'garanapitupulu@example.org', 'Jalan Sukajadi No. 8', 'Tasikmalaya', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ir. Juli Siregar, S.Ked', 'banawilatupono@example.net', 'Gang Ciwastra No. 827', 'Depok', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Zahra Yulianti', 'uwaisgabriella@example.org', 'Jalan Indragiri No. 666', 'Blitar', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Asmadi Prayoga, S.IP', 'siregarbakiono@example.com', 'Gg. Pasir Koja No. 986', 'Metro', 'Lampung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Puput Saragih, S.I.Kom', 'sarah37@example.com', 'Jl. Laswi No. 525', 'Palembang', 'Sumatera Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('H. Adika Pranowo, S.E.I', 'thabibi@example.net', 'Jl. Raya Setiabudhi No. 41', 'Surabaya', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Cengkal Yulianti', 'mulyanikajen@example.org', 'Gg. Jakarta No. 8', 'Bandar Lampung', 'Lampung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gatot Sihombing', 'ysaragih@example.com', 'Gang Jamika No. 54', 'Pontianak', 'Kalimantan Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Cakrabuana Mandasari', 'tantriwastuti@example.com', 'Gg. Jamika No. 8', 'Tegal', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ratna Kurniawan', 'dnarpati@example.net', 'Gg. Cikutra Timur No. 852', 'Semarang', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dina Mandasari', 'victoria83@example.org', 'Jl. Lembong No. 555', 'Jambi', 'Jambi', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Rahmi Prayoga, S.E.', 'sitorusdimaz@example.com', 'Jalan Waringin No. 46', 'Tarakan', 'Kalimantan Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Asmianto Novitasari', 'xmayasari@example.org', 'Jalan W.R. Supratman No. 141', 'Banjarmasin', 'Kalimantan Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Juli Hastuti', 'olga81@example.org', 'Jalan Jakarta No. 719', 'Sabang', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Dadi Budiyanto', 'wkuswandari@example.net', 'Jalan Yos Sudarso No. 806', 'Bandar Lampung', 'Lampung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R. Putu Wasita, M.Ak', 'prabawa41@example.com', 'Jalan Ronggowarsito No. 2', 'Kupang', 'Nusa Tenggara Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Zamira Kuswandari', 'rendy27@example.net', 'Jalan Gegerkalong Hilir No. 25', 'Gorontalo', 'Gorontalo', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Intan Pangestu', 'pwaluyo@example.com', 'Gg. Raya Setiabudhi No. 6', 'Tasikmalaya', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R.A. Yani Sitompul, S.Psi', 'gmanullang@example.net', 'Gang Sadang Serang No. 12', 'Ternate', 'Maluku Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('KH. Maras Tampubolon', 'yahyanuraini@example.net', 'Jl. Sadang Serang No. 937', 'Bekasi', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Elvin Kusumo', 'edi39@example.org', 'Gang Gardujati No. 1', 'Padang', 'Sumatera Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Qori Pranowo, S.Sos', 'queenwidodo@example.net', 'Jalan Tebet Barat Dalam No. 18', 'Blitar', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Najwa Hassanah, S.Psi', 'xanana24@example.net', 'Gang Ronggowarsito No. 540', 'Depok', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Irnanto Sitorus, M.Farm', 'wthamrin@example.com', 'Jl. Antapani Lama No. 4', 'Mamuju', 'Sulawesi Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Rahmi Kusmawati', 'yuninasyiah@example.net', 'Jl. Tebet Barat Dalam No. 6', 'Mamuju', 'Sulawesi Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Jane Saputra', 'ikin56@example.com', 'Jl. Pasir Koja No. 7', 'Pangkalpinang', 'Kepulauan Bangka Belitung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tugiman Nasyiah, M.Pd', 'bakiadi13@example.com', 'Gang Pacuan Kuda No. 7', 'Depok', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R.A. Dalima Nurdiyanti, S.Pd', 'hadi04@example.org', 'Jalan W.R. Supratman No. 491', 'Solo', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ulva Adriansyah', 'lutfanyuliarti@example.org', 'Jl. Ronggowarsito No. 247', 'Kediri', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Hamima Hidayanto, S.Pd', 'ojanuar@example.org', 'Jl. Antapani Lama No. 033', 'Balikpapan', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Kamila Dongoran', 'sihotangheryanto@example.com', 'Gang Ronggowarsito No. 2', 'Denpasar', 'Bali', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Agnes Lazuardi', 'keishasamosir@example.com', 'Gang Siliwangi No. 183', 'Mataram', 'Nusa Tenggara Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Bakiadi Laksita', 'xrahmawati@example.net', 'Jalan Veteran No. 343', 'Padang', 'Sumatera Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Hafshah Haryanti', 'npuspasari@example.org', 'Jalan Otto Iskandardinata No. 743', 'Batam', 'Kepulauan Riau', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Amelia Prasasta', 'qori54@example.net', 'Gang Kapten Muslihat No. 05', 'Langsa', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('KH. Narji Hidayat, S.Ked', 'qadriansyah@example.com', 'Gang W.R. Supratman No. 082', 'Subulussalam', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Lanang Hartati, M.Farm', 'pudjiastutibagus@example.com', 'Gang Lembong No. 0', 'Palopo', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tgk. Widya Usamah, S.IP', 'prabowodadi@example.org', 'Jalan Tebet Barat Dalam No. 8', 'Subulussalam', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R.A. Maida Pudjiastuti, S.I.Kom', 'ika78@example.com', 'Gang Rajawali Timur No. 142', 'Depok', 'Jawa Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Zamira Nainggolan, S.Gz', 'darmajidongoran@example.net', 'Gg. Ronggowarsito No. 2', 'Singkawang', 'Kalimantan Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Rika Wasita, S.Psi', 'daryani96@example.net', 'Jl. HOS. Cokroaminoto No. 9', 'Kendari', 'Sulawesi Tenggara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Eva Budiyanto, S.E.I', 'jail06@example.net', 'Gang Cempaka No. 19', 'Manokwari', 'Papua Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Drs. Danu Hutasoit, M.Ak', 'bagiya05@example.com', 'Jl. Ir. H. Djuanda No. 8', 'Jayapura', 'Papua', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Asman Sihombing', 'isalahudin@example.net', 'Jl. Rajiman No. 877', 'Denpasar', 'Bali', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R.A. Paris Melani, S.Farm', 'mahesahabibi@example.org', 'Gg. Cihampelas No. 1', 'Tangerang', 'Banten', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Zahra Haryanto, S.Pd', 'samosirchelsea@example.com', 'Gang M.H Thamrin No. 27', 'Kediri', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Olivia Kusumo', 'nyanaprakasa@example.net', 'Jalan Jakarta No. 427', 'Tanjung Selor', 'Kalimantan Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Enteng Hidayat', 'kamidin80@example.com', 'Jalan Rajawali Barat No. 41', 'Subulussalam', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Tira Agustina', 'edisitompul@example.com', 'Gang S. Parman No. 0', 'Banjarmasin', 'Kalimantan Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Darman Safitri', 'ufarida@example.org', 'Gang Lembong No. 13', 'Kendari', 'Sulawesi Tenggara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Novi Maryati', 'adityanajmudin@example.org', 'Gang Astana Anyar No. 5', 'Sofifi', 'Maluku Utara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Padma Wibowo', 'dandriani@example.com', 'Gg. Jamika No. 37', 'Madiun', 'Jawa Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Cut Gawati Januar', 'sinagasurya@example.net', 'Jalan Abdul Muis No. 654', 'Makassar', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Garda Pangestu, S.T.', 'lembahramadan@example.com', 'Gang K.H. Wahid Hasyim No. 364', 'Sorong', 'Papua Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Drs. Sari Putra, S.Gz', 'caturanggafarida@example.com', 'Jl. Siliwangi No. 4', 'Tangerang', 'Banten', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('dr. Kartika Ardianto', 'almirasaptono@example.com', 'Gang Jend. A. Yani No. 71', 'Singkawang', 'Kalimantan Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R.A. Indah Wulandari', 'nugrohotugiman@example.net', 'Jl. Raya Setiabudhi No. 593', 'Sungai Penuh', 'Jambi', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Drs. Ellis Anggriawan', 'atma96@example.com', 'Jl. Raya Ujungberung No. 8', 'Lhokseumawe', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Kurnia Ardianto', 'luthfimegantara@example.org', 'Gg. BKR No. 47', 'Langsa', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('R. Elvin Sihombing, S.E.I', 'habibihana@example.com', 'Gang Ahmad Dahlan No. 2', 'Kendari', 'Sulawesi Tenggara', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Septi Puspita', 'fsitompul@example.net', 'Jl. Kapten Muslihat No. 91', 'Bukittinggi', 'Sumatera Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Hana Saefullah', 'irianaandriani@example.org', 'Gang Kutai No. 669', 'Pangkalpinang', 'Kepulauan Bangka Belitung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Jaga Mustofa', 'najamhandayani@example.com', 'Jl. Antapani Lama No. 933', 'Sabang', 'Aceh', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Lutfan Manullang', 'kusumododo@example.com', 'Gg. Ahmad Yani No. 991', 'Palopo', 'Sulawesi Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Drs. Bala Tamba, S.IP', 'garanguwais@example.net', 'Jl. Laswi No. 42', 'Mataram', 'Nusa Tenggara Barat', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Amalia Saefullah', 'olivaputra@example.org', 'Gg. Astana Anyar No. 81', 'Gorontalo', 'Gorontalo', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Drs. Dina Usamah, M.Kom.', 'novitasarisari@example.com', 'Gang Ir. H. Djuanda No. 771', 'Pangkalpinang', 'Kepulauan Bangka Belitung', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gading Ramadan, S.Pd', 'wasitawage@example.com', 'Jl. M.H Thamrin No. 679', 'Palangkaraya', 'Kalimantan Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Ir. Aisyah Damanik, S.E.', 'mustofagalar@example.net', 'Gg. Tebet Barat Dalam No. 500', 'Tegal', 'Jawa Tengah', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Padma Jailani', 'nbudiman@example.com', 'Jl. Erlangga No. 735', 'Banjarmasin', 'Kalimantan Selatan', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Gambira Laksita', 'yuniarradika@example.net', 'Gang HOS. Cokroaminoto No. 02', 'Balikpapan', 'Kalimantan Timur', 'Indonesia');
INSERT INTO pengguna (nama, email, jalan, kota, provinsi, negara) VALUES ('Febi Uwais', 'bmahendra@example.net', 'Gang Rajawali Barat No. 55', 'Tanjungpinang', 'Kepulauan Riau', 'Indonesia');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (1, '+62-0237-290-9860');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (1, '+62 (75) 821 1334');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (2, '082 356 5840');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (3, '(0329) 114-7544');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (4, '+62 (0487) 428 7484');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (4, '+62 (51) 277-8037');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (5, '+62 (0282) 393 1078');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (6, '+62 (89) 346 4149');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (7, '087 647 3911');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (7, '+62 (03) 345 4887');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (7, '+62 (030) 683 2430');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (8, '(0964) 044 3417');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (8, '081 706 4968');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (9, '+62 (908) 808-0866');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (9, '(041) 919 7793');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (10, '+62 (17) 977 6785');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (10, '(0187) 842-8386');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (10, '+62-77-307-7248');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (11, '(0740) 919-3760');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (11, '+62 (048) 906-0479');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (12, '+62 (087) 062 2647');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (12, '+62 (83) 525-9448');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (13, '+62-419-188-6542');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (14, '+62 (52) 264 9551');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (14, '0818853497');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (15, '0816352179');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (16, '+62 (022) 778-4541');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (16, '+62 (0561) 567 3788');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (17, '0810440591');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (18, '+62 (0455) 198 6768');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (18, '+62 (098) 534 6247');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (19, '083 305 0274');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (19, '+62 (0910) 482-4510');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (19, '(0415) 473 0245');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (20, '+62-0011-595-4231');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (20, '+62-0866-679-5101');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (20, '+62 (486) 091 3849');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (21, '+62-709-390-7089');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (21, '(091) 059-9689');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (22, '(011) 515-8771');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (22, '+62 (0867) 109-9718');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (22, '+62 (032) 745-3101');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (23, '(0278) 387-4202');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (23, '+62 (098) 953-3922');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (23, '0855707287');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (24, '+62-080-085-9606');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (25, '(063) 001 0671');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (25, '(0860) 166 7872');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (26, '(0230) 721 7608');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (27, '+62 (0839) 870-7387');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (27, '+62 (0083) 036-4693');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (27, '(037) 116-5104');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (28, '+62 (091) 795 2035');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (29, '085 084 2120');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (29, '+62-476-885-0547');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (30, '0892186389');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (31, '+62 (0740) 471-6882');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (31, '(0794) 924 2395');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (32, '+62 (87) 123 9894');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (32, '(074) 805-2878');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (33, '+62-111-753-2945');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (34, '+62-042-726-7857');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (34, '0827845009');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (34, '(0594) 491-7071');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (35, '+62-040-216-4128');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (35, '+62 (0856) 685 1252');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (35, '089 986 1828');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (36, '+62 (229) 766 3530');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (36, '+62 (0472) 001 0124');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (37, '(0617) 213 1547');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (37, '+62-013-772-9620');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (38, '(098) 917 1061');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (39, '(026) 782-3147');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (40, '(015) 806 1010');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (41, '+62 (716) 726 8036');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (42, '+62 (98) 247 8653');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (42, '+62-0181-375-5120');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (42, '+62 (026) 855-7390');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (43, '+62-881-291-5722');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (43, '+62 (0497) 252 0473');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (43, '084 205 2564');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (44, '+62 (012) 791 1586');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (44, '0822333278');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (45, '+62-03-444-9680');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (46, '+62 (039) 282-1112');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (46, '+62 (723) 641 2959');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (46, '(032) 590-7730');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (47, '(064) 974 4680');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (48, '+62 (016) 749 4922');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (48, '+62 (031) 779-6421');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (49, '(087) 925-8582');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (49, '+62 (676) 507-0506');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (50, '+62 (0076) 644 9370');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (51, '089 850 9806');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (52, '+62 (084) 831-0627');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (53, '+62 (11) 299 9015');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (53, '+62-043-895-4865');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (54, '0860623782');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (54, '(0547) 797 8620');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (54, '(0150) 449 6911');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (55, '084 824 4340');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (55, '+62 (097) 659 1437');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (56, '+62-06-462-8017');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (57, '+62 (28) 895-6800');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (57, '+62 (049) 602-0343');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (57, '+62 (98) 316 7764');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (58, '+62 (97) 143 7188');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (58, '(094) 956-4172');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (59, '+62 (042) 120-3872');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (60, '(0211) 190 1804');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (60, '084 023 5113');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (60, '+62 (326) 104 7213');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (61, '083 435 3424');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (62, '+62-0066-706-2856');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (62, '+62 (28) 330-7484');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (62, '+62 (067) 121-5193');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (63, '+62 (08) 667-3471');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (64, '+62-753-220-3840');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (65, '+62 (07) 136 7299');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (65, '+62-099-416-4545');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (65, '+62 (0752) 949-2986');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (66, '+62-0771-855-9597');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (66, '+62 (0807) 670-5671');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (66, '+62-03-931-8300');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (67, '+62 (099) 746 7089');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (68, '+62-011-591-0343');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (69, '+62 (605) 633-4046');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (69, '+62 (0878) 977-2649');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (70, '(096) 933-5181');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (71, '(0612) 297 8302');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (72, '+62-021-993-5365');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (72, '089 220 2550');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (73, '+62-075-301-9761');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (74, '+62-181-865-1332');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (75, '+62 (075) 818-6103');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (75, '+62 (0105) 043 6854');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (76, '+62-097-181-2830');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (77, '080 520 2023');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (77, '+62-022-652-9883');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (77, '+62-056-161-6297');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (78, '+62 (019) 219 3257');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (78, '(0648) 904 2387');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (78, '+62 (068) 365 4701');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (79, '+62 (041) 843 1461');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (80, '081 703 7042');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (80, '+62 (019) 217-9752');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (80, '+62 (72) 096-9240');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (81, '+62 (066) 492-6534');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (82, '+62 (003) 502-9239');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (82, '+62 (0597) 248-6199');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (83, '+62 (000) 304-6221');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (83, '+62 (208) 305-6787');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (84, '+62 (741) 097-1578');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (84, '+62 (820) 905-4843');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (85, '+62 (626) 128-2970');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (85, '0873928357');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (85, '089 549 0111');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (86, '(047) 040-6173');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (86, '+62-078-935-4518');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (87, '089 880 7757');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (88, '(0772) 670-6873');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (88, '(0939) 013-8925');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (89, '+62 (020) 689 4937');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (89, '+62 (645) 886 2929');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (89, '+62-057-835-6158');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (90, '(0324) 432 6953');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (90, '+62 (067) 960 5996');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (90, '+62-032-482-1666');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (91, '087 314 2094');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (91, '0804619443');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (92, '0836653310');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (92, '(055) 470 1543');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (92, '+62-78-134-7971');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (93, '+62 (117) 395 0407');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (94, '0866820279');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (95, '+62-03-243-6141');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (95, '+62 (22) 927 0679');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (95, '+62 (73) 860-5927');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (96, '+62-028-042-4763');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (97, '+62-0670-805-6920');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (97, '+62 (152) 809-6761');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (98, '+62 (416) 438 0523');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (98, '+62 (40) 200-1832');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (99, '(0917) 665 1177');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (99, '+62 (882) 410 6754');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (100, '+62-025-665-9876');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (101, '+62 (0778) 795 7647');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (101, '+62 (0066) 784-8165');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (101, '0854843065');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (102, '+62 (02) 316 0495');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (102, '+62-005-663-5495');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (102, '+62 (0597) 922-4868');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (103, '+62 (42) 952-4514');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (103, '+62 (006) 211-7879');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (104, '0812967147');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (104, '(0883) 304 3605');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (105, '081 756 8462');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (105, '(058) 076-8773');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (105, '+62 (096) 037 9019');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (106, '(043) 099 5276');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (106, '(0009) 736 5090');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (106, '+62-0805-187-5587');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (107, '+62-82-034-8105');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (108, '(0872) 492-4680');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (109, '+62 (018) 887-5853');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (109, '085 680 3767');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (110, '+62 (0679) 386 5047');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (111, '(0869) 990 3119');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (112, '(0045) 267 7370');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (113, '(0842) 978-7796');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (113, '+62 (194) 262-2909');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (114, '0885625315');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (115, '(056) 198-2183');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (115, '0862469875');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (115, '085 743 4168');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (116, '+62 (376) 421-6177');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (116, '(0391) 545 6951');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (117, '+62 (0679) 068 5007');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (117, '(016) 364 2098');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (117, '+62 (0478) 711 0549');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (118, '(0145) 810-0064');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (118, '+62-096-165-1870');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (118, '+62-03-083-5214');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (119, '+62 (63) 244 1105');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (119, '0874908896');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (120, '0881070265');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (120, '+62-072-227-6268');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (120, '(0944) 757 4836');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (121, '+62-501-066-0320');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (121, '+62-71-556-8854');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (122, '+62 (0967) 120-1473');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (123, '+62 (845) 265-2966');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (124, '+62 (0970) 736 9722');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (125, '+62 (035) 695-1901');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (125, '+62 (086) 813-9146');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (125, '+62-93-621-9978');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (126, '+62 (0430) 348-0390');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (127, '(098) 222-1102');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (127, '+62-084-110-3960');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (128, '+62 (51) 614-3696');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (129, '+62 (076) 640 5103');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (129, '+62-0405-358-8709');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (130, '+62-19-383-0478');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (130, '+62 (0621) 588-8883');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (131, '+62-496-447-7632');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (132, '+62 (0625) 030-7103');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (132, '+62-753-055-0096');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (132, '(036) 066 1519');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (133, '+62 (317) 839 7121');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (133, '+62 (082) 565-7419');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (134, '+62 (0537) 976 8604');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (134, '(0063) 102 3976');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (135, '+62 (891) 284-7460');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (135, '+62-092-480-4575');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (135, '+62 (91) 423-3582');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (136, '(062) 700 3184');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (137, '(043) 979-0362');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (137, '+62 (0739) 209 9102');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (138, '(034) 842-7633');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (138, '(0726) 843-2424');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (138, '+62-564-293-1059');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (139, '(0368) 670-6091');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (139, '+62-0182-878-7631');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (139, '(0242) 743 6448');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (140, '+62-050-940-8310');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (140, '0884936351');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (141, '+62 (0501) 510 0729');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (141, '+62 (074) 298-1606');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (141, '+62-561-998-2448');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (142, '(055) 059 0704');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (143, '(0491) 435-5002');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (143, '+62 (026) 457-8355');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (144, '+62 (042) 317 1055');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (144, '+62 (015) 439-1321');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (145, '+62 (027) 917 0060');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (145, '+62-878-165-6514');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (146, '(0388) 275-2378');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (146, '+62-0342-593-8777');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (147, '+62-919-470-1637');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (147, '+62-084-907-6847');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (147, '+62-0567-065-2479');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (148, '+62 (266) 899-1026');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (148, '+62 (302) 520-0714');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (149, '(0415) 569 5871');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (150, '+62 (044) 486 7646');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (151, '(0680) 882 0417');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (151, '+62 (592) 266-6551');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (151, '+62-015-631-5477');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (152, '+62-0219-485-9907');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (152, '+62 (319) 488 9526');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (152, '+62 (792) 548 9074');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (153, '(074) 672 0649');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (153, '+62 (0751) 501-6951');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (153, '(075) 148 2526');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (154, '(0879) 310-1504');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (154, '0876328619');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (154, '+62 (0792) 432-8206');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (155, '+62-66-650-0876');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (155, '(0914) 296-9543');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (156, '+62 (47) 531-0308');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (156, '+62-079-775-9769');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (156, '+62 (021) 584-8974');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (157, '+62 (095) 898-7252');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (157, '+62 (051) 855 2011');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (157, '+62 (0843) 391-9216');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (158, '+62 (08) 945-5767');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (159, '080 087 3471');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (159, '(0686) 318-4500');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (160, '+62-825-888-1926');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (160, '+62 (0889) 741-0131');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (160, '(0121) 770-5452');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (161, '(068) 620 2056');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (161, '+62 (025) 920 9937');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (162, '(0901) 108-1718');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (163, '+62-0446-196-2355');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (164, '+62-399-192-6928');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (165, '0840009456');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (165, '+62-061-179-5651');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (166, '+62 (39) 893 0910');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (167, '(069) 605 8243');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (168, '+62 (0090) 391-3548');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (168, '+62 (97) 242-0808');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (168, '083 014 7702');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (169, '+62-64-104-3562');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (169, '(0317) 232-1326');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (169, '+62-27-616-8601');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (170, '0828734372');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (170, '+62 (087) 721 9742');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (170, '(050) 703-2268');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (171, '+62 (0624) 401-8590');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (171, '(0608) 666 0465');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (172, '+62-0726-544-1006');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (172, '+62 (344) 753 0388');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (173, '+62 (199) 691 7820');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (173, '+62-093-559-6462');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (174, '+62 (0296) 934-3065');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (175, '+62 (0994) 578 2042');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (175, '088 270 5762');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (175, '+62-090-640-4966');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (176, '(0200) 661 9638');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (177, '+62 (348) 450-0597');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (177, '(097) 297 0309');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (178, '+62 (12) 012-8248');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (179, '+62-0718-197-2499');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (180, '+62 (70) 608 0906');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (181, '+62 (350) 234 9582');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (182, '080 236 5340');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (182, '(0757) 313-3751');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (183, '(0189) 515-6960');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (183, '+62-373-873-5939');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (184, '+62 (06) 996-8137');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (184, '+62 (0156) 729-2447');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (185, '+62-0567-775-1620');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (185, '+62 (025) 693 9197');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (186, '(0105) 743-1238');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (186, '+62 (0218) 041-1458');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (187, '(066) 430-5268');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (188, '(064) 782 2405');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (188, '+62 (0497) 253-0752');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (188, '0811737394');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (189, '+62 (246) 859-6631');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (189, '+62-0252-282-1246');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (189, '+62 (042) 561-8205');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (190, '(0014) 155-0404');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (190, '+62 (73) 505-2347');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (190, '082 434 2873');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (191, '0869894848');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (191, '+62 (0222) 792-1468');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (191, '(0823) 023-2138');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (192, '(0712) 164 9423');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (192, '0857885162');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (192, '(070) 039-6871');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (193, '0875201352');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (193, '(0179) 656-1070');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (194, '(0168) 326 6637');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (194, '086 842 1898');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (195, '(0839) 739 2548');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (196, '(049) 927 6876');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (196, '(0266) 736 7388');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (196, '(013) 358-5612');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (197, '+62 (045) 314-3355');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (197, '+62 (015) 068-0336');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (198, '+62 (72) 799-2589');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (198, '+62-37-130-3432');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (198, '0895129116');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (199, '+62-0603-999-1017');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (199, '(0209) 919-5432');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (200, '(054) 884 2049');
INSERT INTO pengguna_telp (id_user, nomor_telepon) VALUES (200, '(047) 269 2563');
