-- shelter
INSERT INTO shelter (nama, kota, negara) VALUES ('Shelter Animalia Bahagia', 'Dumai', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Animal Rescue Pawtopia Sejahtera', 'Singkawang', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Rumah Singgah Meong Care', 'Tangerang Selatan', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Animal Rescue Kucing Indonesia', 'Madiun', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Animal Rescue Meong Indonesia', 'Tangerang Selatan', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Yayasan PetCare Sejahtera', 'Serang', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Yayasan Animalia Harapan', 'Pekalongan', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Pusat Adopsi Anjing Bandung', 'Balikpapan', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Shelter Pawtopia Rescue', 'Pekanbaru', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Rumah Singgah Pawtopia Indonesia', 'Parepare', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Animal Rescue Paws Sejahtera', 'Semarang', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Animal Rescue Animalia Care', 'Serang', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Animal Rescue Meong Harapan', 'Samarinda', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Pusat Adopsi Satwa Rescue', 'Manado', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Rumah Singgah Kucing Nusantara', 'Banjarbaru', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Shelter PetCare Sejahtera', 'Cimahi', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Animal Rescue Animalia Bandung', 'Sibolga', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Rumah Singgah Animalia Harapan', 'Tangerang Selatan', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Rumah Singgah Satwa Indonesia', 'Serang', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Animal Rescue Animalia Bandung', 'Tanjungbalai', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Pusat Adopsi PetCare Indonesia', 'Bekasi', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Rumah Singgah Pawtopia Care', 'Batam', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Shelter Anjing Indonesia', 'Pekanbaru', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Shelter Paws Harapan', 'Pasuruan', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Animal Rescue Pawtopia Harapan', 'Subulussalam', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Shelter Pawtopia Nusantara', 'Sungai Penuh', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Pusat Adopsi Satwa Nusantara', 'Kupang', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Animal Rescue Anjing Care', 'Pontianak', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Animal Rescue Paws Bandung', 'Padang Sidempuan', 'Indonesia');
INSERT INTO shelter (nama, kota, negara) VALUES ('Shelter PetCare Nusantara', 'Bogor', 'Indonesia');
